/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dbafeb029bdd95510990bea
*
* You will get 10% discount for each one of your friends
* 
*/
package com.testowyprojekt.db.testowyprojekt_db.dtos.infos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE DocumentInfoDto PLEASE EDIT ../DocumentInfo.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the info of Document object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;


public class DocumentBaseInfo {
	
	private Long _id;
	// Attributes
    private Date AddDate;
    private Date AnswerDate;
    private Date AnswerExpireDate;
    private Date DocumentDate;
    private Double Type;
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public Date getAddDate() {
		return AddDate;
	}

	public void setAddDate(Date AddDate) {
		this.AddDate = AddDate;
	}
	public Date getAnswerDate() {
		return AnswerDate;
	}

	public void setAnswerDate(Date AnswerDate) {
		this.AnswerDate = AnswerDate;
	}
	public Date getAnswerExpireDate() {
		return AnswerExpireDate;
	}

	public void setAnswerExpireDate(Date AnswerExpireDate) {
		this.AnswerExpireDate = AnswerExpireDate;
	}
	public Date getDocumentDate() {
		return DocumentDate;
	}

	public void setDocumentDate(Date DocumentDate) {
		this.DocumentDate = DocumentDate;
	}
	public Double getType() {
		return Type;
	}

	public void setType(Double Type) {
		this.Type = Type;
	}
}