/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dbafeb029bdd95510990bea
*
* You will get 10% discount for each one of your friends
* 
*/
package com.testowyprojekt.db.testowyprojekt_db.service.base;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;


import com.testowyprojekt.db.testowyprojekt_db.entity.Document;

import com.testowyprojekt.db.testowyprojekt_db.repositories.DocumentRepository;

@Service
@Transactional
public class DocumentBaseService {

	
	@Autowired
	DocumentRepository documentRepository;


    // CRUD METHODS
    
    // CRUD - CREATE
    
	public Document insert(Document document) {
		return documentRepository.save(document);
	}
	
	// CRUD - REMOVE
    
	public void delete(Long id) {
		documentRepository.delete(id);
	}

	// CRUD - GET ONE
    	
	public Document getOne(Long id) {
		return documentRepository.findOne(id);
	}

    	
    // CRUD - GET LIST
    	
	public List<Document> getAll() {
		List<Document> list = new ArrayList<>();
		documentRepository.findAll().forEach(list::add);
		return list;
	}
	

}
