/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dbafeb029bdd95510990bea
*
* You will get 10% discount for each one of your friends
* 
*/
package com.testowyprojekt.db.testowyprojekt_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE DocumentBase PLEASE EDIT ../Document.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Document object
 * 
 */

import javax.persistence.GeneratedValue;
import javax.persistence.MappedSuperclass;
import javax.persistence.Id;
import javax.persistence.Column;
import java.util.Date;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.FetchType;
import java.util.stream.Collectors;

import com.testowyprojekt.db.testowyprojekt_db.entity.Document;
// Import relations

import com.testowyprojekt.db.testowyprojekt_db.entity.VindicationCase;



@MappedSuperclass
public class DocumentBase {
	
	@Id
	@GeneratedValue
	private Long _id;
	
	// Attributes
	@Column()
    private Date AddDate;
	@Column()
    private Date AnswerDate;
	@Column()
    private Date AnswerExpireDate;
	@Column()
    private Date DocumentDate;
	@Column()
    private Double Type;
	
	@ManyToMany(mappedBy="Document")
	private List<VindicationCase> VindicationCases = new ArrayList<>();
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public Date getAddDate() {
		return AddDate;
	}

	public void setAddDate(Date AddDate) {
		this.AddDate = AddDate;
	}
	public Date getAnswerDate() {
		return AnswerDate;
	}

	public void setAnswerDate(Date AnswerDate) {
		this.AnswerDate = AnswerDate;
	}
	public Date getAnswerExpireDate() {
		return AnswerExpireDate;
	}

	public void setAnswerExpireDate(Date AnswerExpireDate) {
		this.AnswerExpireDate = AnswerExpireDate;
	}
	public Date getDocumentDate() {
		return DocumentDate;
	}

	public void setDocumentDate(Date DocumentDate) {
		this.DocumentDate = DocumentDate;
	}
	public Double getType() {
		return Type;
	}

	public void setType(Double Type) {
		this.Type = Type;
	}
    

    
	// Relations VindicationCase

	public List<VindicationCase> getVindicationCase() {
		return this.VindicationCases;
	}

	public void addVindicationCase(VindicationCase VindicationCase) {
		this.VindicationCases.add(VindicationCase);
	}

	public void removeVindicationCase(VindicationCase VindicationCase) {
		this.VindicationCases.remove(VindicationCase);
	}
	
}