/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dbafeb029bdd95510990bea
*
* You will get 10% discount for each one of your friends
* 
*/

// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// DEBTOR
export const CREATE_DEBTOR_SUCCESS = "CREATE_DEBTOR_SUCCESS";
export const DELETE_DEBTOR_SUCCESS = "DELETE_DEBTOR_SUCCESS";
export const GET_DEBTOR_SUCCESS = "GET_DEBTOR_SUCCESS";
export const LIST_DEBTOR_SUCCESS = "LIST_DEBTOR_SUCCESS";
export const UPDATE_DEBTOR_SUCCESS = "UPDATE_DEBTOR_SUCCESS";

// DOCUMENT
export const CREATE_DOCUMENT_SUCCESS = "CREATE_DOCUMENT_SUCCESS";
export const DELETE_DOCUMENT_SUCCESS = "DELETE_DOCUMENT_SUCCESS";
export const GET_DOCUMENT_SUCCESS = "GET_DOCUMENT_SUCCESS";
export const LIST_DOCUMENT_SUCCESS = "LIST_DOCUMENT_SUCCESS";
export const UPDATE_DOCUMENT_SUCCESS = "UPDATE_DOCUMENT_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// VINDICATIONCASE
export const CREATE_VINDICATIONCASE_SUCCESS = "CREATE_VINDICATIONCASE_SUCCESS";
export const DELETE_VINDICATIONCASE_SUCCESS = "DELETE_VINDICATIONCASE_SUCCESS";
export const FINDBYDEBTOR_VINDICATIONCASE_SUCCESS = "FINDBYDEBTOR_VINDICATIONCASE_SUCCESS";
export const FINDBYDOCUMENT_VINDICATIONCASE_SUCCESS = "FINDBYDOCUMENT_VINDICATIONCASE_SUCCESS";
export const GET_VINDICATIONCASE_SUCCESS = "GET_VINDICATIONCASE_SUCCESS";
export const LIST_VINDICATIONCASE_SUCCESS = "LIST_VINDICATIONCASE_SUCCESS";
export const UPDATE_VINDICATIONCASE_SUCCESS = "UPDATE_VINDICATIONCASE_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
